[test]
preload = ["./src/tests-setup.ts"]

[test.mapping]
"react" = "preact/compat"
"react-dom" = "preact/compat"
"react-dom/client" = "preact/compat"
"react-dom/test-utils" = "preact/test-utils"
"react/jsx-runtime" = "preact/jsx-runtime"
